apiVersion: ENC[AES256_GCM,data:Ng8=,iv:q1QE5sQmbm0szwSLG1aETb6F/h9ktOPOf5v67GObIIA=,tag:3KwK73QI0JvHK48xVfP6Wg==,type:str]
kind: ENC[AES256_GCM,data:ENlJoGl+,iv:4TGrp4QIeVu4690Hfl52eQyM/xpaqolhOiegARiA55c=,tag:ymttn1f2wEjCgPmdc+wUfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:N8RhdPuWX6VeZw==,iv:K0dwVns7drWNwM68rKqiGgrRqQhQkM9yH+bb22maJI0=,tag:NUDL/5nsioi8zzSKjWDXUg==,type:str]
data:
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:5hdOWWE81SkY6COtnQUdUE7aNGnCu7orK55OSJ9EILTfK5TRQrh2wO2t4WZIus5C,iv:Rv2G/jHPZNZ/x3ieBW97xwvz1gqktSzvUpYVO2dLVuI=,tag:QHgQe9PXihs3wFqiVGjvEA==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:s7BEBg9qu5ez64QG/Nh+HKsc55truJY+vjITqeIew6wvY3k9A4cTlVwd5JzZB+/v,iv:15yqSi8EMFHKwa+/nu5F9cL2rRSKaEQys+2ZJhkup2s=,tag:Vg2pASFJ3/cnwklwMnE7rw==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:No0qyNoB4glcgcA0J7UKs8t7f5U/+uA5oc07YP/G73Kv6X5PyOfyB1wm7UbbvVmqDNDFGXboiNY=,iv:lGXuklpR/fp9h0gIrfmh/DO/rIMD/kLU9lDWuwfXPfI=,tag:1Wi6gJ8xPJZ1OQAUgpzJlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ueklhfy0wgrx2kqnndha69cc0e2dn80sdg6ej26c2gvfgd2fctqme6l9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN0RUWlpic29wUTIvY2N4
            MVEwZmRsZmloY1pzZVdjLzVGK0tpcGJVa3o0CjRwbjhKbkNySXg3TnBhejcrRFBM
            SDR0RXUzSitxYnMyQ0tUR0dIK3dWRDAKLS0tIFg1YTd0WkZzcWkxcVhReTVoYm81
            bCs2Yzk0ZzVRb05oUlE4SmpCaEVXVEUKZIanLUpklxMFuZ1toTkspBq2XmBwR7+s
            NaNJXpmVwFfHkkljaLTqE2Fi2NZORa0uO76wOkAhVnRnUZBIFsQIUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-18T01:17:04Z"
    mac: ENC[AES256_GCM,data:rBDRTnX0cJmmHBR/BZ9p70v1pFZ1VRNnfFjs6wEriaYYW6r/wu59z7On3iWh7WdaqgI0w5X3qLa/iDv6UZ50liCNbrscb7NOWQ6Ae3Jm2crvXv4YIJzLJxwAi6cT2c2tcrlDexa4mqaRLmOWXCwUg5/RM8bTF4TVYiyYJI6O8Jo=,iv:XQCeef+W9yXfw3KV7bnifdPRJCE//27jXciYzIdNEaA=,tag:IswKBx8L6ZIQymXdhS/uTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
