name: Build ArgoCD image
on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            ARGOCD_VERSION=2.4.11
            SOPS_VERSION=3.7.3
            HELM_SECRETS_VERSION=4.0.0
          tags: ghcr.io/${{ github.repository }}:v2.4.11
